### ISSUE TITLE
Compatibility with Reimagined World Menu

### ISSUE THREAD

**Issue by vico93** [TrueHorse/Your-Items-To-New-Worlds#4]
I wonder if this mod is compatible with @lamaprogramer's [Reimagined World Menu](https://github.com/lamaprogramer/ReimaginedMenus) ([Modrinth](https://modrinth.com/mod/reimagined-world-menu)) mod.

**Comment by TrueHorse** [comment]
It would be nice if you would test that before opening an issue about it, but if not, which, granted, is likely, I don't think I can do anything about that, or at least I don't know how I could.
But I just released an update with a command to do the same thing in an already created world, so even if you insist on your reimagined world menu, you can still use that. ;)

**Comment by vico93** [comment]
> It would be nice if you would test that before opening an issue about it, but if not, which, granted, is likely, I don't think I can do anything about that, or at least I don't know how I could. But I just released an update with a command to do the same thing in an already created world, so even if you insist on your reimagined world menu, you can still use that. ;)

I'm amazed at your harshness. Impressive! /s
And yeah, i tested with both mods. And i don't see any button to do the copy.
I could try with your mod only but, given your stupidity treating people interested in try it for the first time, i think the better way is either to ask @lamaprogramer to implement this feature straight in Reimagined World Menu or even ask any other developer in Fabric's Discord to make another mod achieving the same feature, because i tend to avoid using mods made by crass on the likes of you.

**Comment by TrueHorse** [comment]
I didn't mean to be harsh. I just don't see the point in supporting such a small mod, if I don't already know how, especially if you can just use the importItems command, which opens the same screen as the button in the world creation menu.

**Comment by williamk-jr** [comment]
Don't go starting wars now, @vico93 @TrueHorse, the reason this mod doesn't work with mine is likely cause of my menu screen code, it doesn't modify the menu, it entirely replaces it, any vanilla tab code is disabled and replaced with my tab code, so any mixins that modify classes disabled by my mod would be useless, compatibility is likely not possible on their end, I would have to do that on my end, which I cant give any promises on, however I will try. This also means that it is not the developers fault for not adding compatibility, so please don't harass them about it as it is likely my fault they aren't compatible.

**Comment by vico93** [comment]
> I didn't mean to be harsh.
Oh ye olde saying: "Who hits always forget, who gets hit doesn't".

> Don't go starting wars now, @vico93 @TrueHorse
I wasn't starting anything. If i was rude on OP i would accept his response, but not.
