### ISSUE TITLE
Items disappear from Sophisticated Backpacks

### ISSUE THREAD

**Issue by MrProton657** [TrueHorse/Your-Items-To-New-Worlds#5]
Items disappear from Sophisticated Backpacks after import into the new world. With Travelers Backpacks mod they don't disappear, because of that it's not a big deal, but I still wanted to inform you. 

Version 1.20.1
your_items_to_new_worlds-1.20-1.1.0.1.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

**Comment by TrueHorse** [comment]
Thank you. Reports are always appreciated, especially when most people don't. (put anecdote here) 😉
Havn't looked at Minecraft code in a while, so I don't immediately have an idea, what the problem might be and unfortunately I also can't promise to make your effort of reporting it worth it by looking at it at some point, because I am currently not very interested in Minecraft modding. Sorry.

**Comment by TrueHorse** [comment]
Ok, looked at it and found the cause. For some reason SophisticatedBackpacks doesn't store the content of the backpack in the normal nbt tag called "tag", but in a seperate nbt called "contentsUuid" and I use a vanilla method to convert the nbt data to items, which of cause doesn't check that nbt.
I could put a Mixin in so it does, even though I would like it more if SophBP would just conform with Minecraft conventions. Would be cleaner. But maybe they have a good reason.
Still no promise I will implement it, but I will consider it. 😉

**Comment by TrueHorse** [comment]
After all this time I unfortunately still have to half disappoint you. My solution from the comment above was completely wrong, but I found out that contents of the backpack are stored in a file called sophisticatedbackpacks.dat, so in theory I just need to read that file and write the relevant contents to the file of the new world. Problem is that that world folder doesn't exist yet on world creation and I don't know the world name yet either, so I can't create it myself. I would need to hold on to the data through world creation and then write it and I don't care enough about it to figure that out.

You can, however, copy that file manually. Its in the data folder in the world folder.
Sorry to disappoint you.
