### ISSUE TITLE
Crash when searching player Forge 1.20.1

### ISSUE THREAD

**Issue by HoodBlah** [TrueHorse/Your-Items-To-New-Worlds#7]
Made new world, imported items from old world. Selected my player name and clicked search, then it crashed.

[debug.log](https://github.com/user-attachments/files/16228600/debug.log)
[latest.log](https://github.com/user-attachments/files/16228601/latest.log)

**Comment by TrueHorse** [comment]
On first glance that looks very weird. Thanks for the report. 🙂

**Comment by TrueHorse** [comment]
There seems to have been a problem when it tried to display an item from Vic's Point Blank, but I don't know Geckolib, so I don't understand the specifics.
I put a workaround in the upcoming update (will probably upload the fabric version today), so it doesn't crash.
